### PR TITLE
Update code in `nl2sql.ipynb` notebook - Changed the approach to explain the SQL tables to the model

### PR DESCRIPTION
**Pull request by fmquaglia**
It is using a domain-specific language already understood by the model. This results in a more compact system prompt that allows for a more nuanced data model description. This should result in fewer tokens consumed by the system prompts and better maintainability, allowing for a richer data definition.

This might not be ideal for an educational exercise because it adds to the cognitive load (Wait... what? What is this DBML thing?), but I figured I would show it to you, anyway.

From 

```jupyter
 # ...

context.append( {'role':'system', 'content':"""
first table:
{
  "tableName": "employees",
  "fields": [
    {
      "nombre": "ID_usr",
      "tipo": "int"
    },
    {
      "nombre": "name",
      "tipo": "string"
    }
  ]
}
"""
})

context.append( {'role':'system', 'content':"""
second table:
{
  "tableName": "salary",
  "fields": [
    {
      "nombre": "ID_usr",
      "type": "int"
    },
    {
      "name": "year",
      "type": "date"
    },
    {
      "name": "salary",
      "type": "float"
    }
  ]
}
"""
})

context.append( {'role':'system', 'content':"""
third table:
{
  "tablename": "studies",
  "fields": [
    {
      "name": "ID",
      "type": "int"
    },
    {
      "name": "ID_usr",
      "type": "int"
    },
    {
      "name": "educational level",
      "type": "int"
    },
    {
      "name": "Institution",
      "type": "string"
    },
    {
      "name": "Years",
      "type": "date"
    }
    {
      "name": "Speciality",
      "type": "string"
    }
  ]
}
"""
})

# ...
```

To

```jupyter
 # ...

context.append( {'role':'system', 'content':"""
This is the definition of your database tables:

```dbml
Table employees {
  ID_usr int [pk]
  name string
}

Table salary {
  ID_usr int [ref: > employees.ID_usr]
  year date
  salary float
}

Table studies {
  ID int [pk]
  ID_usr int [ref: > employees.ID_usr]
  educational_level int
  Institution string
  Years date
  Speciality string
}
```
"""
})

# ...
```

### CODE REVIEW

**Comment by fmquaglia** [comment]
Notice that GitHub gets confused by the markdown in the system prompt, and it does not render the code properly in the PR description.

**Comment by fmquaglia** [comment]
I rebased on top of the latest additions to `main`.

**Comment by peremartra** [comment]
Hi @fmquaglia,

As you know, this notebook is part of a course, and it’s just a basic, initial approach to creating an NL2SQL solution. In a more advanced lesson, we have this notebook:
[6_1_nl2sql_prompt_OpenAI.ipynb](https://github.com/peremartra/Large-Language-Model-Notebooks-Course/blob/main/P1-NL2SQL/6_1_nl2sql_prompt_OpenAI.ipynb),
which uses a very similar structure in the prompt to what you are presenting here, based on this paper:
https://arxiv.org/abs/2305.11853.

However, I prefer to keep this more basic and somewhat incorrect approach here, and introduce the more accurate method later when the students have a stronger foundation of knowledge.

**Comment by peremartra** [comment]
Just figured that we can upload the notebook with a different name, and with some explanations in the header, explaining that this is a better solution. 

rename the notebook to: 1_2b-Easy_NL2SQL.ipynb. 

and please, add a by line in the header with your name and a link to your github profile, or linked profile, the one you prefer.

**Comment by peremartra** [comment]
> @peremartra I totally missed this message. I'll try to have it done as you suggest by the end of this week, sir. Thank you!



> @peremartra I totally missed this message. I'll try to have it done as you suggest by the end of this week, sir. Thank you!



> @peremartra I totally missed this message. I'll try to have it done as you suggest by the end of this week, sir. Thank you!

My Fault @fmquaglia! Thanks to you, waiting for you modifications :-)

**Comment by fmquaglia** [comment]
@peremartra Sorry, my wife called me to have dinner, and I completely forgot to send you a comment letting you know that what you requested has been done. Man, thanks for letting me contribute to this project. It makes me happy. Thank you!

**Comment by peremartra** [comment]
[image: image.png]
Thanks to you Fabricio!

**Comment by peremartra** [comment]
Hi Fabricio, I added a link to the notebook in the readme.md of the course,
and i'll promote the notebook on likedin and twitter in the next days,
Thanks for the contribution!

**Pull request merged**
